import React from 'react';
import { IVAnalysisResult } from '../types';
import { AlertTriangle, CheckCircle2, AlertOctagon, Info, FileText, Activity, Scale, Droplet, Ruler, Share2, Copy, Check } from 'lucide-react';

interface AnalysisResultCardProps {
  result: IVAnalysisResult;
}

const PHLEBITIS_SCALE = [
  { grade: 0, criteria: "No clinical symptoms" },
  { grade: 1, criteria: "Erythema at access site with or without pain" },
  { grade: 2, criteria: "Pain at access site with erythema and/or edema" },
  { grade: 3, criteria: "Pain at access site with erythema, streak formation, palpable venous cord" },
  { grade: 4, criteria: "Pain at access site with erythema, streak formation, palpable venous cord >1 inch (2.5cm) in length, and/or purulent drainage" },
];

const LEAKAGE_SCALE = [
  { grade: 0, criteria: "No clinical symptoms" },
  { grade: 1, criteria: "Skin blanched; Edema <1 inch (2.5cm); Cool to touch; With or without pain" },
  { grade: 2, criteria: "Skin blanched; Edema 1-6 inches (2.5-15cm); Cool to touch; With or without pain" },
  { grade: 3, criteria: "Skin blanched, translucent; Edema >6 inches (>15cm); Cool to touch; Mild-moderate pain; Possible numbness" },
  { grade: 4, criteria: "Skin tight, leaking, discolored, bruised, swollen; Deep pitting edema; Circulatory impairment; Infiltration of any amount of blood product, irritant, or vesticant" },
];

const AnalysisResultCard: React.FC<AnalysisResultCardProps> = ({ result }) => {
  const [copied, setCopied] = React.useState(false);
  const isNormal = result.status.toLowerCase().includes('normal') || result.status.includes('ปกติ');
  const isDanger = result.status.toLowerCase().includes('extravasation') || result.status.toLowerCase().includes('necrosis') || result.status.includes('รั่วซึมรุนแรง');
  const isPhlebitis = result.status.toLowerCase().includes('phlebitis') || result.status.includes('หลอดเลือดอักเสบ');
  const isLeakage = result.status.toLowerCase().includes('extravasation') || result.status.toLowerCase().includes('infiltration') || result.status.includes('รั่วซึม');
  const isExtravasation = result.status.toLowerCase().includes('extravasation') || result.status.includes('necrosis');
  const leakageTitle = isExtravasation ? "INS Extravasation Scale Reference" : "INS Infiltration Scale Reference";

  const getGrade = (severityStr: string): number | null => {
    const match = severityStr.match(/(\d)/);
    return match ? parseInt(match[0]) : null;
  };

  const currentGrade = getGrade(result.severity);

  const getLeakageReasoning = (grade: number) => {
    if (isExtravasation && grade === 4) return "Automatic Grade 4: Vesicant fluid leakage detected.";
    switch (grade) {
      case 1: return "AI Measurement: Localized edema estimated < 1 inch (2.5cm).";
      case 2: return "AI Measurement: Edema field spreads 1-6 inches (2.5-15cm).";
      case 3: return "AI Measurement: Extensive edema > 6 inches (>15cm).";
      case 4: return "AI Detection: Deep pitting edema or circulatory compromise.";
      default: return "Correlated with visual markers.";
    }
  };

  const getPhlebitisReasoning = (grade: number) => {
    switch (grade) {
      case 1: return "AI Observation: Erythema localized at access site.";
      case 2: return "AI Observation: Erythema with reported pain/edema.";
      case 3: return "AI Measurement: Red streak/Palpable cord detected < 1 inch.";
      case 4: return "AI Measurement: Palpable venous cord > 1 inch.";
      default: return "Correlated with visual markers.";
    }
  };

  const handleShare = async () => {
    const reportText = `
[IV GUARDIAN AI - DIAGNOSTIC REPORT]
-----------------------------------
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

STATUS: ${result.status.toUpperCase()}
SEVERITY: ${result.severity}

VISUAL EVIDENCE:
${result.visualEvidence}

NURSING INTERVENTION:
${result.nursingIntervention}

SAFETY WARNING:
${result.safetyWarning}

-----------------------------------
Generated by IV Guardian AI (INS Standards)
    `.trim();

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'IV Guardian AI Report',
          text: reportText,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      // Fallback: Copy to clipboard
      try {
        await navigator.clipboard.writeText(reportText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        alert('Could not copy to clipboard');
      }
    }
  };

  const statusConfig = isNormal 
    ? { color: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-100', icon: <CheckCircle2 size={28} /> }
    : isDanger 
      ? { color: 'text-rose-600', bg: 'bg-rose-50', border: 'border-rose-100', icon: <AlertOctagon size={28} /> }
      : { color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-100', icon: <AlertTriangle size={28} /> };

  return (
    <div className="bg-white rounded-2xl shadow-xl shadow-slate-200/60 overflow-hidden w-full max-w-2xl mx-auto border border-slate-200 animate-fade-in-up">
      
      {/* Diagnostic Header */}
      <div className="border-b border-slate-100 bg-slate-50/50 p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
           <div className="flex items-center gap-2 mb-1">
             <span className="w-2 h-2 rounded-full bg-teal-500 animate-pulse"></span>
             <span className="text-[10px] font-mono text-slate-400 uppercase tracking-widest">Analysis Completed</span>
           </div>
           <h2 className="text-xl font-bold text-slate-800 font-sans">Diagnostic Report</h2>
        </div>
        <div className="flex items-center gap-3">
           <button 
             onClick={handleShare}
             className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-sm font-bold transition-all shadow-md shadow-indigo-200 active:scale-95"
           >
             {copied ? <Check size={16} /> : <Share2 size={16} />}
             {copied ? 'COPIED' : 'SHARE REPORT'}
           </button>
           <div className="hidden sm:flex flex-col items-end">
             <span className="text-[10px] text-slate-400 font-mono uppercase">Ref ID</span>
             <span className="text-xs font-mono font-semibold text-slate-700">{Math.random().toString(36).substring(7).toUpperCase()}</span>
           </div>
        </div>
      </div>

      {/* Primary Result Banner */}
      <div className={`px-8 py-8 flex items-start gap-6 border-b border-slate-100/50 ${statusConfig.bg}`}>
         <div className={`p-3 bg-white rounded-xl shadow-sm border ${statusConfig.border} ${statusConfig.color}`}>
            {statusConfig.icon}
         </div>
         <div className="flex-1">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Primary Finding</h3>
            <div className={`text-3xl font-bold tracking-tight mb-2 ${statusConfig.color}`}>{result.status}</div>
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-white border border-slate-200 text-slate-600 shadow-sm">
              SEVERITY: {result.severity}
            </div>
         </div>
      </div>

      <div className="p-8 space-y-8">
        
        {/* Evidence Grid */}
        <div className="grid md:grid-cols-[1fr,1.5fr] gap-8">
           
           {/* Visual Evidence */}
           <div className="space-y-3">
              <h4 className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider">
                 <Info size={14} /> Visual Markers
              </h4>
              <div className="text-sm text-slate-600 leading-relaxed bg-slate-50 p-4 rounded-lg border border-slate-100 h-full">
                 {result.visualEvidence}
              </div>
           </div>

           {/* Intervention */}
           <div className="space-y-3">
              <h4 className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider">
                 <Activity size={14} /> Recommended Protocol
              </h4>
              <div className="text-sm text-slate-800 leading-relaxed bg-blue-50/50 p-4 rounded-lg border border-blue-100/50 shadow-sm h-full font-medium">
                 {result.nursingIntervention}
              </div>
           </div>
        </div>

        {/* PHLEBITIS SPECIFIC SCALE SECTION */}
        {isPhlebitis && (
          <div className="border-t border-slate-100 pt-8 animate-fade-in">
            <h4 className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">
              <Scale size={14} /> INS Phlebitis Scale Reference
            </h4>
            
            <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
              {PHLEBITIS_SCALE.map((item) => {
                const isActive = currentGrade === item.grade;
                const reasoning = getPhlebitisReasoning(item.grade);
                return (
                  <div key={item.grade} className={`flex flex-col sm:flex-row sm:items-center p-4 border-b last:border-0 border-slate-100 transition-colors ${isActive ? 'bg-amber-50/70' : 'hover:bg-slate-50'}`}>
                    <div className="sm:w-24 mb-2 sm:mb-0 flex-shrink-0">
                      <span className={`inline-block px-2 py-1 rounded text-xs font-bold font-mono border ${isActive ? 'bg-amber-100 text-amber-700 border-amber-200' : 'bg-slate-100 text-slate-500 border-slate-200'}`}>GRADE {item.grade}</span>
                    </div>
                    <div className="flex-1">
                      <p className={`text-sm ${isActive ? 'text-slate-900 font-medium' : 'text-slate-500'}`}>{item.criteria}</p>
                      {isActive && (
                        <div className="mt-2 text-xs text-amber-700 bg-amber-100/50 p-2 rounded border border-amber-100 flex items-start gap-2">
                           <CheckCircle2 size={14} className="mt-0.5 flex-shrink-0" />
                           <div className="flex flex-col">
                            <span className="font-bold mb-0.5">AI Determination:</span>
                            <span>{reasoning}</span>
                           </div>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* EXTRAVASATION / INFILTRATION SCALE SECTION */}
        {isLeakage && (
          <div className="border-t border-slate-100 pt-8 animate-fade-in">
            <h4 className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">
              <Droplet size={14} /> {leakageTitle}
            </h4>
            <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
              {LEAKAGE_SCALE.map((item) => {
                const isActive = currentGrade === item.grade;
                const reasoning = getLeakageReasoning(item.grade);
                return (
                  <div key={item.grade} className={`flex flex-col sm:flex-row sm:items-center p-4 border-b last:border-0 border-slate-100 transition-colors ${isActive ? 'bg-amber-50/70' : 'hover:bg-slate-50'}`}>
                    <div className="sm:w-24 mb-2 sm:mb-0 flex-shrink-0">
                      <span className={`inline-block px-2 py-1 rounded text-xs font-bold font-mono border ${isActive ? 'bg-amber-100 text-amber-700 border-amber-200' : 'bg-slate-100 text-slate-500 border-slate-200'}`}>GRADE {item.grade}</span>
                    </div>
                    <div className="flex-1">
                      <p className={`text-sm ${isActive ? 'text-slate-900 font-medium' : 'text-slate-500'}`}>{item.criteria}</p>
                      {isActive && (
                        <div className="mt-2 text-xs text-amber-700 bg-amber-100/50 p-2 rounded border border-amber-100 flex items-start gap-2">
                           <CheckCircle2 size={14} className="mt-0.5 flex-shrink-0" />
                           <div className="flex flex-col">
                            <span className="font-bold mb-0.5">AI Determination:</span>
                            <span>{reasoning}</span>
                           </div>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Disclaimer / Footer */}
        <div className="mt-4 pt-6 border-t border-slate-100 flex items-start gap-3">
           <FileText size={16} className="text-slate-300 mt-0.5" />
           <p className="text-[11px] text-slate-400 leading-5">
              <strong className="text-slate-500">Disclaimer:</strong> {result.safetyWarning}
              <br/>This report is generated by AI (Gemini 3 Pro) to support clinical decision-making. It does not replace professional medical diagnosis.
           </p>
        </div>

      </div>
    </div>
  );
};

export default AnalysisResultCard;